site_name: Laravel Todo List Practice
site_description: Simple Laravel task/todo list app (practice project)
repo_url: https://github.com/laravel/laravel
repo_name: Repository

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Configuration: configuration.md
  - App routes: routes.md
  - Development: development.md
